# Generated by Django 5.1.7 on 2025-04-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'لپ تاپ'), ('SmartPhone', 'گوشی هوشمند'), ('Tablet', 'تبلت'), ('SmartWatch', 'ساعت هوشمند'), ('Accessories', 'لوازم جانبی')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
